---
- name: Installing tools
  ansible.builtin.apt: >
    name={{ item }}
    state=present
  with_items:
    - ntp
    - python3
    - tcpdump
    - wget
    - openssl
    - curl
    - git
    - net-tools
    - apt-transport-https
    # - iptables-persistent