---
- name: Disable swap (if configured).
  command: swapoff -a
  tags: ['skip_ansible_lint']
  
- name: Disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
    