---
- import_tasks: disable-swap.yml
- import_tasks: add-modprobe-modules.yml

- name: Let iptables see bridged traffic
  copy:
    dest: "/etc/sysctl.d/k8s.conf"
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
    mode: 0644

- name: Containerd configuration
  shell: "{{ item }}"
  with_items: 
    - containerd config default | tee /etc/containerd/config.toml
    - sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
  notify: restart containerd
  tags: ['skip_ansible_lint']

- import_tasks: k8s-install.yml
- name: Check Kubernetes init
  stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_init_stat


# Set up control plane.
#- include_tasks: control-plane-setup.yml
#  when: kubernetes_role == 'control_plane'  