# advertised host IP for kubelet. This affects network plugin config. Take caution
ip: "{{ ip | default(fallback_ips[hosts]) }}{{ (',' + ip6) if enable_dual_stack_networks and ip6 is defined else '' }}"
