---
- name: Nodes configuration 
  hosts: all
  become: true
  remote_user: astorf
  roles:
    - set-hosts
    - set-hostname
    - set-time-zone
    - install-tools
  tags:
    - node-config

- name: install kubernetes
  hosts: all
  become: true
  remote_user: astorf
  roles:
    - install-containerd
    #- install-docker
    - install-kubernetes
  tags:
    - install-kube


    
...   